name: Deploy to ECS

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: lks-gatus
  ECS_SERVICE: lks-gatus-service1
  ECS_CLUSTER: lks-oss-cluster-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

- name: Configure AWS credentials
  uses: aws-actions/configure-aws-credentials@v2
  with:
    role-to-assume: arn:aws:iam::015817814783:role/LabRole
    aws-region: us-east-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS \
          --password-stdin 015817814783.dkr.ecr.us-east-1.amazonaws.com

      - name: Build image
        run: |
          docker build -t $ECR_REPOSITORY .

      - name: Tag image
        run: |
          docker tag $ECR_REPOSITORY:latest \
          015817814783.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:latest

      - name: Push image
        run: |
          docker push 015817814783.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --force-new-deployment